//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRCFaceTracking.Avalonia.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VRCFaceTracking.Avalonia.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Text {
            get {
                return ResourceManager.GetString("About.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRCFaceTracking.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRCFaceTracking.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Appearance_Text {
            get {
                return ResourceManager.GetString("Appearance.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;toast launch=&quot;action=ToastClick&quot;&gt;
        ///      &lt;visual&gt;
        ///      &lt;binding template=&quot;ToastGeneric&quot;&gt;
        ///      &lt;text&gt;App Notification&lt;/text&gt;
        ///      &lt;text&gt;&lt;/text&gt;
        ///      &lt;image placement=&quot;appLogoOverride&quot; hint-crop=&quot;circle&quot; src=&quot;{0}Assets/WindowIcon.ico&quot;/&gt;
        ///      &lt;/binding&gt;
        ///      &lt;/visual&gt;
        ///      &lt;actions&gt;
        ///      &lt;action content=&quot;Settings&quot; arguments=&quot;action=Settings&quot;/&gt;
        ///      &lt;/actions&gt;
        ///      &lt;/toast&gt;.
        /// </summary>
        public static string AppNotificationSamplePayload {
            get {
                return ResourceManager.GetString("AppNotificationSamplePayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author_Text {
            get {
                return ResourceManager.GetString("Author.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Start when SteamVR is launched.
        /// </summary>
        public static string AutoStartSettings_Description {
            get {
                return ResourceManager.GetString("AutoStartSettings.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Start.
        /// </summary>
        public static string AutoStartSettings_Header {
            get {
                return ResourceManager.GetString("AutoStartSettings.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar Status.
        /// </summary>
        public static string AvatarStatus_Text {
            get {
                return ResourceManager.GetString("AvatarStatus.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File a bug report.
        /// </summary>
        public static string BugRequestCard_Header {
            get {
                return ResourceManager.GetString("BugRequestCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate.
        /// </summary>
        public static string CalibrateButton_Content {
            get {
                return ResourceManager.GetString("CalibrateButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles whether or not calibration is enabled.
        /// </summary>
        public static string CalibrationEnabledToggle_Description {
            get {
                return ResourceManager.GetString("CalibrationEnabledToggle.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration Enabled.
        /// </summary>
        public static string CalibrationEnabledToggle_Header {
            get {
                return ResourceManager.GetString("CalibrationEnabledToggle.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how much of an influence your facial expressions have on overall calibration
        ///      over time.
        /// </summary>
        public static string CalibrationInfluenceSlider_Description {
            get {
                return ResourceManager.GetString("CalibrationInfluenceSlider.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration Influence.
        /// </summary>
        public static string CalibrationInfluenceSlider_Header {
            get {
                return ResourceManager.GetString("CalibrationInfluenceSlider.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweak tracking data to your heart&apos;s content.
        /// </summary>
        public static string CalibrationSettings_Description {
            get {
                return ResourceManager.GetString("CalibrationSettings.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration Settings.
        /// </summary>
        public static string CalibrationSettings_Header {
            get {
                return ResourceManager.GetString("CalibrationSettings.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To clone this repository.
        /// </summary>
        public static string CloneRepoCard_Header {
            get {
                return ResourceManager.GetString("CloneRepoCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slowly calibrates to your facial expressions over time.
        /// </summary>
        public static string ContCalibrationToggle_Description {
            get {
                return ResourceManager.GetString("ContCalibrationToggle.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous Calibration.
        /// </summary>
        public static string ContCalibrationToggle_Header {
            get {
                return ResourceManager.GetString("ContCalibrationToggle.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2023 VRCFaceTracking. All rights reserved..
        /// </summary>
        public static string Copyright_Description {
            get {
                return ResourceManager.GetString("Copyright.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nerds who made this all possible &lt;3.
        /// </summary>
        public static string Credits_Description {
            get {
                return ResourceManager.GetString("Credits.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies &amp; references.
        /// </summary>
        public static string Dependencies_Header {
            get {
                return ResourceManager.GetString("Dependencies.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description_Text {
            get {
                return ResourceManager.GetString("Description.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS CODE AND INFORMATION IS PROVIDED ‘AS IS’ WITHOUT WARRANTY OF ANY KIND, EITHER
        ///      EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY
        ///      AND/OR FITNESS FOR A PARTICULAR PURPOSE..
        /// </summary>
        public static string Disclaimer_Header {
            get {
                return ResourceManager.GetString("Disclaimer.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string Downloads_Text {
            get {
                return ResourceManager.GetString("Downloads.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Files Here to Install.
        /// </summary>
        public static string DragNDrop_DropFilesHere {
            get {
                return ResourceManager.GetString("DragNDrop.DropFilesHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release to add modules to VRCFaceTracking.
        /// </summary>
        public static string DragNDrop_ReleaseFiles {
            get {
                return ResourceManager.GetString("DragNDrop.ReleaseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Tracking Active.
        /// </summary>
        public static string EyeTrackingActive_Text {
            get {
                return ResourceManager.GetString("EyeTrackingActive.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Tracking Active.
        /// </summary>
        public static string FaceTrackingActive_Text {
            get {
                return ResourceManager.GetString("FaceTrackingActive.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force VRCFT to unload and reinitialize all modules.
        /// </summary>
        public static string ForceReInitButton_Description {
            get {
                return ResourceManager.GetString("ForceReInitButton.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Re-Initialize.
        /// </summary>
        public static string ForceReInitButton_Header {
            get {
                return ResourceManager.GetString("ForceReInitButton.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces sending of all parameters every frame by forcing relevancy.
        /// </summary>
        public static string ForceRelevancyToggle_Description {
            get {
                return ResourceManager.GetString("ForceRelevancyToggle.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Relevancy.
        /// </summary>
        public static string ForceRelevancyToggle_Header {
            get {
                return ResourceManager.GetString("ForceRelevancyToggle.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stare at your tongue I guess?.
        /// </summary>
        public static string HardwareDebug_Description {
            get {
                return ResourceManager.GetString("HardwareDebug.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Debug.
        /// </summary>
        public static string HardwareDebug_Header {
            get {
                return ResourceManager.GetString("HardwareDebug.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        public static string LastUpdated_Text {
            get {
                return ResourceManager.GetString("LastUpdated.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Parameters.
        /// </summary>
        public static string LegacyParameters_Text {
            get {
                return ResourceManager.GetString("LegacyParameters.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an item from the list..
        /// </summary>
        public static string ListDetails_NoSelection_Text {
            get {
                return ResourceManager.GetString("ListDetails_NoSelection.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening on Port:.
        /// </summary>
        public static string Listening_on_Port_Text {
            get {
                return ResourceManager.GetString("Listening_on_Port.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Test Avatar Detected.
        /// </summary>
        public static string LocalTestAvatar_Text {
            get {
                return ResourceManager.GetString("LocalTestAvatar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Test Avatars are not supported and will cause issues.
        /// </summary>
        public static string LocalTestAvatarTooltip_Content {
            get {
                return ResourceManager.GetString("LocalTestAvatarTooltip.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Page.
        /// </summary>
        public static string ModulePage_Text {
            get {
                return ResourceManager.GetString("ModulePage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an item from the list..
        /// </summary>
        public static string ModuleRegistry_NoSelection_Text {
            get {
                return ResourceManager.GetString("ModuleRegistry_NoSelection.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msgs/sec Incoming.
        /// </summary>
        public static string msIncoming_Text {
            get {
                return ResourceManager.GetString("msIncoming.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msgs/sec Outgoing.
        /// </summary>
        public static string msOutgoing_Text {
            get {
                return ResourceManager.GetString("msOutgoing.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install some from here!.
        /// </summary>
        public static string no_modules_installed_warning_ButtonText {
            get {
                return ResourceManager.GetString("no_modules_installed_warning.ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You appear to have no modules installed..
        /// </summary>
        public static string no_modules_installed_warning_Description {
            get {
                return ResourceManager.GetString("no_modules_installed_warning.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Modules Installed.
        /// </summary>
        public static string no_modules_installed_warning_Title {
            get {
                return ResourceManager.GetString("no_modules_installed_warning.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Local Storage.
        /// </summary>
        public static string OpenLocalStorageCard_Header {
            get {
                return ResourceManager.GetString("OpenLocalStorageCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We noticed your OSC was turned off in VRChat, we&apos;ve just enabled it for you. If the game
        ///      was open when this happened, you may need to manually enable it from your raidal menu. If not,
        ///      you should be good to go!.
        /// </summary>
        public static string osc_was_disabled_warning_Description {
            get {
                return ResourceManager.GetString("osc_was_disabled_warning.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSC Settings Modified.
        /// </summary>
        public static string osc_was_disabled_warning_Title {
            get {
                return ResourceManager.GetString("osc_was_disabled_warning.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where should OSC Data be sent?.
        /// </summary>
        public static string OscSettings_Description {
            get {
                return ResourceManager.GetString("OscSettings.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSC Address.
        /// </summary>
        public static string OscSettings_Header {
            get {
                return ResourceManager.GetString("OscSettings.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSC Status.
        /// </summary>
        public static string OSCStatus_Text {
            get {
                return ResourceManager.GetString("OSCStatus.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Parameters_Text {
            get {
                return ResourceManager.GetString("Parameters.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicyCard_Header {
            get {
                return ResourceManager.GetString("PrivacyPolicyCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating_Text {
            get {
                return ResourceManager.GetString("Rating.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Initialize.
        /// </summary>
        public static string ReInitButton_Content {
            get {
                return ResourceManager.GetString("ReInitButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all VRChat OSC config data (will be regenerated when avatar is reloaded).
        /// </summary>
        public static string ResetAvatarConfButton_Description {
            get {
                return ResourceManager.GetString("ResetAvatarConfButton.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset VRChat Configs.
        /// </summary>
        public static string ResetAvatarConfButton_Header {
            get {
                return ResourceManager.GetString("ResetAvatarConfButton.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetButton_Content {
            get {
                return ResourceManager.GetString("ResetButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all data stored by VRCFT in your AppData folder.
        /// </summary>
        public static string ResetVRCFTButton_Description {
            get {
                return ResourceManager.GetString("ResetVRCFTButton.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset VRCFT.
        /// </summary>
        public static string ResetVRCFTButton_Header {
            get {
                return ResourceManager.GetString("ResetVRCFTButton.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger, danger. High voltage...
        /// </summary>
        public static string RiskySettings_Description {
            get {
                return ResourceManager.GetString("RiskySettings.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risky Settings.
        /// </summary>
        public static string RiskySettings_Header {
            get {
                return ResourceManager.GetString("RiskySettings.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending on Port:.
        /// </summary>
        public static string Sending_on_Port_Text {
            get {
                return ResourceManager.GetString("Sending_on_Port.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRChat OSC App to allow AV3 Avatars to interact with eye and lip tracking runtimes.
        /// </summary>
        public static string Settings_About_Text {
            get {
                return ResourceManager.GetString("Settings_About.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRChat OSC App to allow AV3 Avatars to interact with eye and lip tracking runtimes.
        /// </summary>
        public static string Settings_AboutDescription_Text {
            get {
                return ResourceManager.GetString("Settings_AboutDescription.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string Settings_Personalization_Text {
            get {
                return ResourceManager.GetString("Settings_Personalization.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Settings_Theme_Dark_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Dark.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Settings_Theme_Default_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Default.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Settings_Theme_Light_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Light.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Settings_Theme_Text {
            get {
                return ResourceManager.GetString("Settings_Theme.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string SettingsPage_PrivacyTermsLink_Content {
            get {
                return ResourceManager.GetString("SettingsPage_PrivacyTermsLink.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/benaclejames/VRCFaceTracking.
        /// </summary>
        public static string SettingsPage_PrivacyTermsLink_NavigateUri {
            get {
                return ResourceManager.GetString("SettingsPage_PrivacyTermsLink.NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListDetails.
        /// </summary>
        public static string Shell_ListDetails_Content {
            get {
                return ResourceManager.GetString("Shell_ListDetails.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Shell_Main_Content {
            get {
                return ResourceManager.GetString("Shell_Main.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Registry.
        /// </summary>
        public static string Shell_ModuleRegistry_Content {
            get {
                return ResourceManager.GetString("Shell_ModuleRegistry.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Shell_Output_Content {
            get {
                return ResourceManager.GetString("Shell_Output.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Shell_Parameters_Content {
            get {
                return ResourceManager.GetString("Shell_Parameters.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Settings.
        /// </summary>
        public static string Shell_TrackingSettings_Content {
            get {
                return ResourceManager.GetString("Shell_TrackingSettings.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which app theme to display.
        /// </summary>
        public static string ThemeSettings_Description {
            get {
                return ResourceManager.GetString("ThemeSettings.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App theme.
        /// </summary>
        public static string ThemeSettings_Header {
            get {
                return ResourceManager.GetString("ThemeSettings.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Tracking.
        /// </summary>
        public static string ToggleTracking_Content {
            get {
                return ResourceManager.GetString("ToggleTracking.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heighten the influence your expressions make on calibration temporarily.
        /// </summary>
        public static string TrackingCalibrateButton_Description {
            get {
                return ResourceManager.GetString("TrackingCalibrateButton.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate.
        /// </summary>
        public static string TrackingCalibrateButton_Header {
            get {
                return ResourceManager.GetString("TrackingCalibrateButton.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Instructions.
        /// </summary>
        public static string UsageInstructions_Text {
            get {
                return ResourceManager.GetString("UsageInstructions.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version_Text {
            get {
                return ResourceManager.GetString("Version.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your rating.
        /// </summary>
        public static string YourRating_Text {
            get {
                return ResourceManager.GetString("YourRating.Text", resourceCulture);
            }
        }
    }
}
