//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRCFaceTracking.Avalonia.Assets {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("VRCFaceTracking.Avalonia.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }

        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }

        public static string Shell_Main_Content {
            get {
                return ResourceManager.GetString("Shell_Main.Content", resourceCulture);
            }
        }

        public static string ListDetails_NoSelection_Text {
            get {
                return ResourceManager.GetString("ListDetails_NoSelection.Text", resourceCulture);
            }
        }

        public static string Shell_ListDetails_Content {
            get {
                return ResourceManager.GetString("Shell_ListDetails.Content", resourceCulture);
            }
        }

        public static string Settings_Personalization_Text {
            get {
                return ResourceManager.GetString("Settings_Personalization.Text", resourceCulture);
            }
        }

        public static string Settings_Theme_Text {
            get {
                return ResourceManager.GetString("Settings_Theme.Text", resourceCulture);
            }
        }

        public static string Settings_Theme_Light_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Light.Content", resourceCulture);
            }
        }

        public static string Settings_Theme_Dark_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Dark.Content", resourceCulture);
            }
        }

        public static string Settings_Theme_Default_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Default.Content", resourceCulture);
            }
        }

        public static string Settings_About_Text {
            get {
                return ResourceManager.GetString("Settings_About.Text", resourceCulture);
            }
        }

        public static string Settings_AboutDescription_Text {
            get {
                return ResourceManager.GetString("Settings_AboutDescription.Text", resourceCulture);
            }
        }

        public static string SettingsPage_PrivacyTermsLink_Content {
            get {
                return ResourceManager.GetString("SettingsPage_PrivacyTermsLink.Content", resourceCulture);
            }
        }

        public static string SettingsPage_PrivacyTermsLink_NavigateUri {
            get {
                return ResourceManager.GetString("SettingsPage_PrivacyTermsLink.NavigateUri", resourceCulture);
            }
        }

        public static string AppNotificationSamplePayload {
            get {
                return ResourceManager.GetString("AppNotificationSamplePayload", resourceCulture);
            }
        }

        public static string Shell_Output_Content {
            get {
                return ResourceManager.GetString("Shell_Output.Content", resourceCulture);
            }
        }

        public static string Shell_Parameters_Content {
            get {
                return ResourceManager.GetString("Shell_Parameters.Content", resourceCulture);
            }
        }

        public static string ModuleRegistry_NoSelection_Text {
            get {
                return ResourceManager.GetString("ModuleRegistry_NoSelection.Text", resourceCulture);
            }
        }

        public static string Shell_ModuleRegistry_Content {
            get {
                return ResourceManager.GetString("Shell_ModuleRegistry.Content", resourceCulture);
            }
        }

        public static string About_Text {
            get {
                return ResourceManager.GetString("About.Text", resourceCulture);
            }
        }

        public static string Appearance_Text {
            get {
                return ResourceManager.GetString("Appearance.Text", resourceCulture);
            }
        }

        public static string Author_Text {
            get {
                return ResourceManager.GetString("Author.Text", resourceCulture);
            }
        }

        public static string AvatarStatus_Text {
            get {
                return ResourceManager.GetString("AvatarStatus.Text", resourceCulture);
            }
        }

        public static string LocalTestAvatar_Text {
            get {
                return ResourceManager.GetString("LocalTestAvatar.Text", resourceCulture);
            }
        }

        public static string LocalTestAvatarTooltip_Content {
            get {
                return ResourceManager.GetString("LocalTestAvatarTooltip.Content", resourceCulture);
            }
        }

        public static string Copyright_Description {
            get {
                return ResourceManager.GetString("Copyright.Description", resourceCulture);
            }
        }

        public static string Credits_Description {
            get {
                return ResourceManager.GetString("Credits.Description", resourceCulture);
            }
        }

        public static string Dependencies_Header {
            get {
                return ResourceManager.GetString("Dependencies.Header", resourceCulture);
            }
        }

        public static string Description_Text {
            get {
                return ResourceManager.GetString("Description.Text", resourceCulture);
            }
        }

        public static string Disclaimer_Header {
            get {
                return ResourceManager.GetString("Disclaimer.Header", resourceCulture);
            }
        }

        public static string Downloads_Text {
            get {
                return ResourceManager.GetString("Downloads.Text", resourceCulture);
            }
        }

        public static string EyeTrackingActive_Text {
            get {
                return ResourceManager.GetString("EyeTrackingActive.Text", resourceCulture);
            }
        }

        public static string FaceTrackingActive_Text {
            get {
                return ResourceManager.GetString("FaceTrackingActive.Text", resourceCulture);
            }
        }

        public static string BugRequestCard_Header {
            get {
                return ResourceManager.GetString("BugRequestCard.Header", resourceCulture);
            }
        }

        public static string PrivacyPolicyCard_Header {
            get {
                return ResourceManager.GetString("PrivacyPolicyCard.Header", resourceCulture);
            }
        }

        public static string LastUpdated_Text {
            get {
                return ResourceManager.GetString("LastUpdated.Text", resourceCulture);
            }
        }

        public static string LegacyParameters_Text {
            get {
                return ResourceManager.GetString("LegacyParameters.Text", resourceCulture);
            }
        }

        public static string Listening_on_Port_Text {
            get {
                return ResourceManager.GetString("Listening_on_Port.Text", resourceCulture);
            }
        }

        public static string ModulePage_Text {
            get {
                return ResourceManager.GetString("ModulePage.Text", resourceCulture);
            }
        }

        public static string msIncoming_Text {
            get {
                return ResourceManager.GetString("msIncoming.Text", resourceCulture);
            }
        }

        public static string msOutgoing_Text {
            get {
                return ResourceManager.GetString("msOutgoing.Text", resourceCulture);
            }
        }

        public static string no_modules_installed_warning_Title {
            get {
                return ResourceManager.GetString("no_modules_installed_warning.Title", resourceCulture);
            }
        }

        public static string no_modules_installed_warning_ButtonText {
            get {
                return ResourceManager.GetString("no_modules_installed_warning.ButtonText", resourceCulture);
            }
        }

        public static string osc_was_disabled_warning_Title {
            get {
                return ResourceManager.GetString("osc_was_disabled_warning.Title", resourceCulture);
            }
        }

        public static string osc_was_disabled_warning_Description {
            get {
                return ResourceManager.GetString("osc_was_disabled_warning.Description", resourceCulture);
            }
        }

        public static string OSCStatus_Text {
            get {
                return ResourceManager.GetString("OSCStatus.Text", resourceCulture);
            }
        }

        public static string Parameters_Text {
            get {
                return ResourceManager.GetString("Parameters.Text", resourceCulture);
            }
        }

        public static string Rating_Text {
            get {
                return ResourceManager.GetString("Rating.Text", resourceCulture);
            }
        }

        public static string ThemeSettings_Header {
            get {
                return ResourceManager.GetString("ThemeSettings.Header", resourceCulture);
            }
        }

        public static string ThemeSettings_Description {
            get {
                return ResourceManager.GetString("ThemeSettings.Description", resourceCulture);
            }
        }

        public static string Sending_on_Port_Text {
            get {
                return ResourceManager.GetString("Sending_on_Port.Text", resourceCulture);
            }
        }

        public static string ToggleTracking_Content {
            get {
                return ResourceManager.GetString("ToggleTracking.Content", resourceCulture);
            }
        }

        public static string CloneRepoCard_Header {
            get {
                return ResourceManager.GetString("CloneRepoCard.Header", resourceCulture);
            }
        }

        public static string OpenLocalStorageCard_Header {
            get {
                return ResourceManager.GetString("OpenLocalStorageCard.Header", resourceCulture);
            }
        }

        public static string UsageInstructions_Text {
            get {
                return ResourceManager.GetString("UsageInstructions.Text", resourceCulture);
            }
        }

        public static string Version_Text {
            get {
                return ResourceManager.GetString("Version.Text", resourceCulture);
            }
        }

        public static string OscSettings_Header {
            get {
                return ResourceManager.GetString("OscSettings.Header", resourceCulture);
            }
        }

        public static string OscSettings_Description {
            get {
                return ResourceManager.GetString("OscSettings.Description", resourceCulture);
            }
        }

        public static string no_modules_installed_warning_Description {
            get {
                return ResourceManager.GetString("no_modules_installed_warning.Description", resourceCulture);
            }
        }

        public static string CalibrationSettings_Header {
            get {
                return ResourceManager.GetString("CalibrationSettings.Header", resourceCulture);
            }
        }

        public static string CalibrationSettings_Description {
            get {
                return ResourceManager.GetString("CalibrationSettings.Description", resourceCulture);
            }
        }

        public static string RiskySettings_Header {
            get {
                return ResourceManager.GetString("RiskySettings.Header", resourceCulture);
            }
        }

        public static string RiskySettings_Description {
            get {
                return ResourceManager.GetString("RiskySettings.Description", resourceCulture);
            }
        }

        public static string AutoStartSettings_Header {
            get {
                return ResourceManager.GetString("AutoStartSettings.Header", resourceCulture);
            }
        }

        public static string AutoStartSettings_Description {
            get {
                return ResourceManager.GetString("AutoStartSettings.Description", resourceCulture);
            }
        }

        public static string CalibrationEnabledToggle_Header {
            get {
                return ResourceManager.GetString("CalibrationEnabledToggle.Header", resourceCulture);
            }
        }

        public static string CalibrationEnabledToggle_Description {
            get {
                return ResourceManager.GetString("CalibrationEnabledToggle.Description", resourceCulture);
            }
        }

        public static string ContCalibrationToggle_Header {
            get {
                return ResourceManager.GetString("ContCalibrationToggle.Header", resourceCulture);
            }
        }

        public static string ContCalibrationToggle_Description {
            get {
                return ResourceManager.GetString("ContCalibrationToggle.Description", resourceCulture);
            }
        }

        public static string TrackingCalibrateButton_Header {
            get {
                return ResourceManager.GetString("TrackingCalibrateButton.Header", resourceCulture);
            }
        }

        public static string TrackingCalibrateButton_Description {
            get {
                return ResourceManager.GetString("TrackingCalibrateButton.Description", resourceCulture);
            }
        }

        public static string CalibrationInfluenceSlider_Header {
            get {
                return ResourceManager.GetString("CalibrationInfluenceSlider.Header", resourceCulture);
            }
        }

        public static string CalibrationInfluenceSlider_Description {
            get {
                return ResourceManager.GetString("CalibrationInfluenceSlider.Description", resourceCulture);
            }
        }

        public static string CalibrateButton_Content {
            get {
                return ResourceManager.GetString("CalibrateButton.Content", resourceCulture);
            }
        }

        public static string ForceReInitButton_Description {
            get {
                return ResourceManager.GetString("ForceReInitButton.Description", resourceCulture);
            }
        }

        public static string ForceReInitButton_Header {
            get {
                return ResourceManager.GetString("ForceReInitButton.Header", resourceCulture);
            }
        }

        public static string ForceRelevancyToggle_Description {
            get {
                return ResourceManager.GetString("ForceRelevancyToggle.Description", resourceCulture);
            }
        }

        public static string ForceRelevancyToggle_Header {
            get {
                return ResourceManager.GetString("ForceRelevancyToggle.Header", resourceCulture);
            }
        }

        public static string ReInitButton_Content {
            get {
                return ResourceManager.GetString("ReInitButton.Content", resourceCulture);
            }
        }

        public static string ResetAvatarConfButton_Description {
            get {
                return ResourceManager.GetString("ResetAvatarConfButton.Description", resourceCulture);
            }
        }

        public static string ResetAvatarConfButton_Header {
            get {
                return ResourceManager.GetString("ResetAvatarConfButton.Header", resourceCulture);
            }
        }

        public static string ResetButton_Content {
            get {
                return ResourceManager.GetString("ResetButton.Content", resourceCulture);
            }
        }

        public static string ResetVRCFTButton_Description {
            get {
                return ResourceManager.GetString("ResetVRCFTButton.Description", resourceCulture);
            }
        }

        public static string ResetVRCFTButton_Header {
            get {
                return ResourceManager.GetString("ResetVRCFTButton.Header", resourceCulture);
            }
        }

        public static string HardwareDebug_Header {
            get {
                return ResourceManager.GetString("HardwareDebug.Header", resourceCulture);
            }
        }

        public static string HardwareDebug_Description {
            get {
                return ResourceManager.GetString("HardwareDebug.Description", resourceCulture);
            }
        }

        public static string Shell_TrackingSettings_Content {
            get {
                return ResourceManager.GetString("Shell_TrackingSettings.Content", resourceCulture);
            }
        }
    }
}
